export const SITE = {
  website: "https://skalej.dev/",
  author: "Saeid Kaleji",
  profile: "https://skalej.dev/about/",
  desc: "Software engineer based in Germany. Building tools for e-invoicing, language learning, and developer productivity.",
  title: "Saeid Kaleji",
  ogImage: "astropaper-og.jpg",
  lightAndDarkMode: true,
  postPerIndex: 6,
  postPerPage: 6,
  scheduledPostMargin: 15 * 60 * 1000,
  showArchives: true,
  showBackButton: true,
  editPost: {
    enabled: false,
    text: "Edit page",
    url: "https://github.com/YOURUSER/YOURREPO/edit/main/",
  },
  dynamicOgImage: true,
  dir: "ltr",
  lang: "en",
  timezone: "Europe/Berlin",
} as const;
